<?php 

$GYOSYU_DAIBUNRUI = array(
"特殊作業員",
"普通作業員",
"軽作業員",
"造園工",
"法面工",
"とび工",
"石工",
"ブロック工",
"電工",
"鉄筋工",
"鉄骨工",
"塗装工",
"溶接工",
"運転⼿（特殊）",
"運転⼿（一般）",
"さく岩工",
"トンネル特殊工",
"トンネル作業員",
"トンネル世話役",
"橋りょう特殊工",
"橋りょう塗装工",
"橋りょう世話役",
"土木一般世話役",
"高級船員",
"普通船員",
"潜水士",
"軌道工",
"型わく工",
"大工",
"左官",
"配管工",
"はつり工",
"防水工",
"板⾦工",
"タイル工",
"サッシ工",
"屋根ふき工",
"内装工",
"ガラス工",
"建具工",
"ダクト工",
"保温工",
"建築ブロック工",
"設備機械工",
"交通誘導員A",
"交通誘導員B",
"その他（施工）",
"その他（管理）",
"その他（技師）",
"その他"
);

$GYOSYU_SYOBUNRUI = array();
$GYOSYU_SYOBUNRUI["特殊作業員"]=array("特殊作業員",
"コンクリート工",
"コンクリート圧送工",
"コンクリートカッター工",
"あと施工アンカー工",
"ボーリング工",
"アンカー工",
"グラウト工",
"土工",
"地盤改良工事工",
);
$GYOSYU_SYOBUNRUI["普通作業員"]=array("普通作業員",
"掘削工",
);
$GYOSYU_SYOBUNRUI["軽作業員"]=array("軽作業員",
"清掃作業員",
);
$GYOSYU_SYOBUNRUI["造園工"]=array("造園工",
"造園修景工",
"公園設備工",
"植栽工",
"芝張工",
"植木職",
);
$GYOSYU_SYOBUNRUI["法面工"]=array("法面工",
);
$GYOSYU_SYOBUNRUI["とび工"]=array("とび工",
"足場とび工",
"鉄骨とび工",
"重量とび工",
"建築とび工",
"くい打ち工",
"土止め工",
);
$GYOSYU_SYOBUNRUI["石工"]=array("石工",
);
$GYOSYU_SYOBUNRUI["ブロック工"]=array("ブロック工",
);
$GYOSYU_SYOBUNRUI["電工"]=array("電気工",
"電気通信工",
"送配電線工",
"火災報知器据付工",
"普通作業員（電気工）",
"その他電気設備",
);
$GYOSYU_SYOBUNRUI["鉄筋工"]=array("鉄筋工",
"鉄筋圧接工",
);
$GYOSYU_SYOBUNRUI["鉄骨工"]=array("鉄骨工",
"鋼構造物工",
);
$GYOSYU_SYOBUNRUI["塗装工"]=array("塗装工",
"吹付塗装工",
);
$GYOSYU_SYOBUNRUI["溶接工"]=array("溶接工",
"かじ工",
);
$GYOSYU_SYOBUNRUI["運転⼿（特殊）"]=array("運転⼿（特殊）・建設機械運転工",
"しゅんせつ工",
"コンクリートポンプ車運転工",
"舗装機械運転工",
"海上工事機械運転工",
"掘削機械運転工",
"くい打機運転工",
"クレーン運転工",
);
$GYOSYU_SYOBUNRUI["運転⼿（一般）"]=array("運転⼿（一般）",
"ダンプカー運転⼿",
"資材運搬工",
);
$GYOSYU_SYOBUNRUI["さく岩工"]=array("さく岩工",
);
$GYOSYU_SYOBUNRUI["トンネル特殊工"]=array("トンネル工（特殊作業員）",
);
$GYOSYU_SYOBUNRUI["トンネル作業員"]=array("トンネル工（普通作業員）",
"シールド工（普通作業員）",
);
$GYOSYU_SYOBUNRUI["トンネル世話役"]=array("トンネル工（世話役）",
);
$GYOSYU_SYOBUNRUI["橋りょう特殊工"]=array("橋りょう特殊工",
);
$GYOSYU_SYOBUNRUI["橋りょう塗装工"]=array("橋りょう塗装工",
);
$GYOSYU_SYOBUNRUI["橋りょう世話役"]=array("橋りょう世話役",
);
$GYOSYU_SYOBUNRUI["土木一般世話役"]=array("土木一般世話役",
);
$GYOSYU_SYOBUNRUI["高級船員"]=array("高級船員",
);
$GYOSYU_SYOBUNRUI["普通船員"]=array("普通船員",
);
$GYOSYU_SYOBUNRUI["潜水士"]=array("潜水士",
);
$GYOSYU_SYOBUNRUI["軌道工"]=array("軌道工",
);
$GYOSYU_SYOBUNRUI["型わく工"]=array("型わく工",
"型枠解体工",
"墨出し大工",
);
$GYOSYU_SYOBUNRUI["大工"]=array("大工",
"宮大工",
"造作大工",
"組立大工",
"営繕大工",
"木工",
"大工（ツーバイフォー工法）",
"外装大工",
"大工（丸太組工法）",
);
$GYOSYU_SYOBUNRUI["左官"]=array("左官工",
"吹付工",
"外壁仕上工",
);
$GYOSYU_SYOBUNRUI["配管工"]=array("配管工",
"配管工（給排水・衛生）",
"配管工（冷暖房）",
"配管工（ガス）",
"配管工（プラント）",
"ボイラー設置工",
"ポンプ設置工",
"浄化設備工",
"計装工（給排水衛生設備）",
"水道施設工",
"消防施設工",
"ガス器具取付工",
"冷凍空調設備工",
);
$GYOSYU_SYOBUNRUI["はつり工"]=array("はつり工",
);
$GYOSYU_SYOBUNRUI["防水工"]=array("防水工",
"塗膜防水工",
"シート防水工",
"アスファルト防水工",
"シーリング防水工",
"ウレタン防水工",
);
$GYOSYU_SYOBUNRUI["板⾦工"]=array("板⾦工",
"⾦物工",
"⾦属工",
);
$GYOSYU_SYOBUNRUI["タイル工"]=array("タイル工",
);
$GYOSYU_SYOBUNRUI["サッシ工"]=array("サッシ工",
);
$GYOSYU_SYOBUNRUI["屋根ふき工"]=array("屋根工",
);
$GYOSYU_SYOBUNRUI["内装工"]=array("内装工",
"内装仕上工",
"軽鉄工",
"ボード張り工",
"床張り工",
"壁装（クロス）工",
"ユニット工",
"フローリング工",
"二重床工",
"表具師",
"経師",
);
$GYOSYU_SYOBUNRUI["ガラス工"]=array("ガラス工",
"ガラスブロック工",
);
$GYOSYU_SYOBUNRUI["建具工"]=array("建具工",
"シャッター工",
"鋼製建具工",
"カーテンウォール工",
);
$GYOSYU_SYOBUNRUI["ダクト工"]=array("ダクト工（空気調和設備）",
"塗装工（空気調和設備）",
);
$GYOSYU_SYOBUNRUI["保温工"]=array("保温工",
"熱絶縁工",
"防露工",
"耐火被覆工（湿式）",
"耐火被覆工（乾式）",
"耐火被覆工（塗装）",
);
$GYOSYU_SYOBUNRUI["建築ブロック工"]=array("建築ブロック工",
"ALC工",
);
$GYOSYU_SYOBUNRUI["設備機械工"]=array("設備機械工",
"機械器具設置工",
"計装工",
"冷凍空調設備工",
"昇降機技能工（エレベータ工）",
);
$GYOSYU_SYOBUNRUI["交通誘導員A"]=array("交通誘導警備員（検定合格者）",
);
$GYOSYU_SYOBUNRUI["交通誘導員B"]=array("交通誘導警備員",
);
$GYOSYU_SYOBUNRUI["その他（施工）"]=array("舗装工",
"アスファルト舗装工",
"道路標識設置工",
"路面標示設置工（区画線工）",
"フェンス工",
"エクステリア工（外構工）",
"運動施設工",
"看板工",
"解体工",
"解体工（コンクリート工作物）",
"ＰＣ工",
"切断穿孔工",
"仕上多能工",
"アスベスト除去工",
"移動･揚重工（場内小運搬）",
"その他",
"建築測量工",
);
$GYOSYU_SYOBUNRUI["その他（管理）"]=array("その他",
"現場監督（建築）",
"現場監督（土木）",
"現場監督（電気）",
"現場監督（空調衛生その他設備）",
"設計担当者",
"現場監督（機械）",
);
$GYOSYU_SYOBUNRUI["その他（技師）"]=array("測量工",
"調査工",
"地質調査工",
"非破壊検査技術者",
);
$GYOSYU_SYOBUNRUI["その他"]=array("その他",
"事務担当者",
);

function create_gyosyudaibunruioption_html(){
 global $GYOSYU_DAIBUNRUI;
 
 echo '<option value="">-選択-</option>';
 foreach($GYOSYU_DAIBUNRUI as $gd){
  echo '<option value="'.$gd.'">'.$gd.'</option>';
 }
}

function create_gyosyusyobunruioption_html(){
 global $GYOSYU_DAIBUNRUI;
 global $GYOSYU_SYOBUNRUI;
 
 echo '<option value="">-選択-</option>';
 foreach($GYOSYU_DAIBUNRUI as $gd){
  foreach($GYOSYU_SYOBUNRUI[$gd] as $gs){
   echo '<option value="'.$gs.'" class="'.$gd.'">'.$gs.'</option>';
  }
 }
}

?>
